// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth_jwt.proto

package io.github.ctlove0523.auth.jwt.samples.grpc;

public interface HelloRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:grpc.HelloRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();

    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
    getNameBytes();
}
